version: '3.8'
services:
  pyspark:

    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: pyspark-container

    ports:
      - "8888:8888"

    volumes:
      - ./:/app

    working_dir: /app

    environment:
      - PYSPARK_PYTHON=python3

    stdin_open: true
    tty: true